from __future__ import annotations

import hashlib
import io
import json
import shutil
import wave
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest
from sqlalchemy import func, select
from sqlalchemy.orm import Session

import app.services.sync_bundle as sync_bundle_module
from app.db import SessionLocal
from app.errors import AppError
from app.models import (
    Artifact,
    Project,
    SyncDeleteTombstone,
    SyncEntityRevision,
    SyncStagedArtifact,
    SyncTrustedPeer,
)
from app.services.paths import project_root
from app.services.sync_bundle import (
    DEFAULT_PROVIDER_DEVICE_ID,
    export_sync_bundle,
    import_sync_bundle,
)
from app.services.sync_identity import source_hash_to_project_id
from app.services.sync_revisions import (
    CURRENT_REVISION_STATE,
    revision_payload_sha256,
    sanitize_revision_payload,
)
from app.services.sync_trust import get_or_create_local_identity
from app.utils.hashing import file_sha256


@dataclass(frozen=True)
class BundleProjectFixture:
    project_id: str
    root: Path
    source_artifact_id: str
    stem_artifact_id: str
    source_relative_path: str
    stem_relative_path: str
    artifact_hashes: dict[str, str]
    artifact_sizes: dict[str, int]


def test_export_sync_bundle_creates_sync_safe_layout(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "bundle"
    with SessionLocal() as session:
        fixture = _create_project_with_artifacts(session, tmp_path)
        result = export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-export",
        )

    metadata = _read_json(bundle_root / "bundle.json")
    manifest_path = bundle_root / "projects" / f"{fixture.project_id}.json"
    manifest = _read_json(manifest_path)
    content_hashes = {
        artifact["content_sha256"]
        for artifact in manifest["artifacts"]
    }
    expected_files = {
        "bundle.json",
        f"projects/{fixture.project_id}.json",
        *{
            f"blobs/sha256/{content_hash[:2]}/{content_hash}"
            for content_hash in content_hashes
        },
    }

    assert result.project_count == 1
    assert result.content_sha256s == sorted(content_hashes)
    assert metadata["kind"] == "tuneforge.sync_bundle"
    assert metadata["version"] == "1"
    assert metadata["project_manifests"] == [
        {
            "content_sha256": file_sha256(manifest_path),
            "path": f"projects/{fixture.project_id}.json",
            "project_id": fixture.project_id,
            "size_bytes": manifest_path.stat().st_size,
        }
    ]
    assert metadata["content_sha256s"] == sorted(content_hashes)
    assert metadata["peer_inventory"] == [
        {
            "device_id": "peer-bundle-export",
            "available_content_sha256": sorted(content_hashes),
        }
    ]
    assert _bundle_files(bundle_root) == expected_files
    _assert_no_absolute_local_paths(metadata, (tmp_path, fixture.root))
    _assert_no_absolute_local_paths(manifest, (tmp_path, fixture.root))
    _assert_no_raw_app_data_entries(metadata)
    _assert_no_raw_app_data_entries(manifest)


@pytest.mark.parametrize(
    ("relative_path", "is_dir"),
    [
        ("tuneforge.sqlite", False),
        ("settings.json", False),
        ("cache", True),
        ("logs", True),
    ],
)
def test_export_sync_bundle_rejects_unsafe_existing_root_entries(
    client: object,
    tmp_path: Path,
    relative_path: str,
    is_dir: bool,
) -> None:
    bundle_root = tmp_path / "hostile-bundle"
    unsafe_path = bundle_root / relative_path
    if is_dir:
        unsafe_path.mkdir(parents=True)
    else:
        unsafe_path.parent.mkdir(parents=True)
        unsafe_path.write_bytes(b"raw app data")

    with SessionLocal() as session:
        with pytest.raises(AppError) as exc:
            export_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == "SYNC_BUNDLE_EXPORT_ROOT_UNSAFE"


def test_export_sync_bundle_allows_syncthing_metadata_entries(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "syncthing-bundle"
    (bundle_root / ".stfolder").mkdir(parents=True)
    (bundle_root / ".stfolder" / "syncthing-folder-test.txt").write_text(
        "syncthing marker\n",
        encoding="utf-8",
    )
    (bundle_root / ".stignore").write_text("// generated by syncthing\n", encoding="utf-8")

    with SessionLocal() as session:
        fixture = _create_project_with_artifacts(session, tmp_path)
        result = export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )

    assert result.project_count == 1
    assert (bundle_root / ".stfolder").is_dir()
    assert (bundle_root / ".stfolder" / "syncthing-folder-test.txt").is_file()
    assert (bundle_root / ".stignore").is_file()
    assert (bundle_root / "bundle.json").is_file()


def test_export_sync_bundle_rejects_nested_stfolder_directories(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "nested-stfolder-bundle"
    nested_stfolder_entry = bundle_root / ".stfolder" / "nested"
    nested_stfolder_entry.mkdir(parents=True)

    with SessionLocal() as session:
        with pytest.raises(AppError) as exc:
            export_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == "SYNC_BUNDLE_EXPORT_ROOT_UNSAFE"


def test_export_sync_bundle_rejects_symlink_in_existing_root(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "symlink-bundle"
    projects_root = bundle_root / "projects"
    projects_root.mkdir(parents=True)
    outside_file = tmp_path / "outside.json"
    outside_file.write_text("{}", encoding="utf-8")
    try:
        (projects_root / "project.json").symlink_to(outside_file)
    except (NotImplementedError, OSError) as exc:
        pytest.skip(f"symlinks unavailable: {exc}")

    with SessionLocal() as session:
        with pytest.raises(AppError) as exc:
            export_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == "SYNC_BUNDLE_EXPORT_ROOT_UNSAFE"


def test_import_sync_bundle_stages_blobs_and_imports_through_reconciliation(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "bundle"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, "peer-bundle-import")
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-import",
        )
        session.commit()

        _delete_live_project(session, fixture)
        session.commit()

        result = import_sync_bundle(
            session,
            bundle_root=bundle_root,
        )
        session.commit()

        project = session.get(Project, fixture.project_id)
        source_artifact = session.get(Artifact, fixture.source_artifact_id)
        stem_artifact = session.get(Artifact, fixture.stem_artifact_id)
        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert result.project_count == 1
    assert result.staged_artifact_count == 2
    assert result.apply_result.summary.failed_actions == 0
    assert any(
        entry.action.action_type == "import_project_manifest"
        and entry.status == "applied"
        for entry in result.apply_result.results
    )
    assert staged_count == 0
    assert project is not None
    assert project.sync_status == "local"
    assert source_artifact is not None
    assert stem_artifact is not None
    assert Path(source_artifact.path).exists()
    assert Path(stem_artifact.path).exists()
    assert source_artifact.content_sha256 == fixture.artifact_hashes[fixture.source_artifact_id]
    assert stem_artifact.content_sha256 == fixture.artifact_hashes[fixture.stem_artifact_id]


def test_import_sync_bundle_allows_override_to_trusted_inventory_provider_with_full_hashes(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "bundle-inventory-provider-override"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, "peer-bundle-metadata")
        _ensure_trusted_peer(session, "peer-bundle-inventory")
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-metadata",
        )
        session.commit()

        metadata_path = bundle_root / "bundle.json"
        metadata = _read_json(metadata_path)
        content_sha256s = metadata["content_sha256s"]
        assert isinstance(content_sha256s, list)
        metadata["peer_inventory"] = [
            {
                "device_id": "peer-bundle-metadata",
                "available_content_sha256": content_sha256s,
            },
            {
                "device_id": "peer-bundle-inventory",
                "available_content_sha256": content_sha256s,
            },
        ]
        metadata_path.write_text(json.dumps(metadata), encoding="utf-8")

        _delete_live_project(session, fixture)
        session.commit()

        result = import_sync_bundle(
            session,
            bundle_root=bundle_root,
            provider_device_id="peer-bundle-inventory",
        )
        session.commit()

        project = session.get(Project, fixture.project_id)

    assert result.project_count == 1
    assert result.staged_artifact_count == 2
    assert result.apply_result.summary.failed_actions == 0
    assert result.peer_inventory == [
        {
            "device_id": "peer-bundle-inventory",
            "available_content_sha256": sorted(content_sha256s),
        }
    ]
    assert project is not None
    assert project.sync_status == "local"


def test_import_sync_bundle_rejects_untrusted_metadata_provider_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-untrusted-provider"
    with SessionLocal() as session:
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-untrusted",
        )
        session.commit()

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_UNTRUSTED"
    assert staged_count == 0


def test_import_sync_bundle_rejects_untrusted_matching_provider_override_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-untrusted-override"
    with SessionLocal() as session:
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-untrusted-override",
        )
        session.commit()

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(
                session,
                bundle_root=bundle_root,
                provider_device_id="peer-bundle-untrusted-override",
            )

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_UNTRUSTED"
    assert staged_count == 0


def test_import_sync_bundle_rejects_mismatched_trusted_provider_override_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-mismatched-override"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, "peer-bundle-source")
        _ensure_trusted_peer(session, "peer-bundle-other")
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-source",
        )
        session.commit()

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(
                session,
                bundle_root=bundle_root,
                provider_device_id="peer-bundle-other",
            )

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_MISMATCH"
    assert exc.value.details == {
        "source": "bundle_metadata",
        "provider_device_id": "peer-bundle-other",
        "metadata_provider_device_id": "peer-bundle-source",
        "peer_inventory_provider_device_ids": ["peer-bundle-source"],
    }
    assert staged_count == 0


def test_import_sync_bundle_rejects_mismatched_inventory_provider_override_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-mismatched-inventory-override"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, DEFAULT_PROVIDER_DEVICE_ID)
        _ensure_trusted_peer(session, "peer-bundle-other")
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )
        session.commit()

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(
                session,
                bundle_root=bundle_root,
                provider_device_id="peer-bundle-other",
            )

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_MISMATCH"
    assert exc.value.details == {
        "source": "peer_inventory",
        "provider_device_id": "peer-bundle-other",
        "metadata_provider_device_id": None,
        "peer_inventory_provider_device_ids": [DEFAULT_PROVIDER_DEVICE_ID],
    }
    assert staged_count == 0


def test_import_sync_bundle_rejects_selected_provider_without_full_inventory_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-selected-provider-empty-inventory"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, DEFAULT_PROVIDER_DEVICE_ID)
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )
        session.commit()

        metadata_path = bundle_root / "bundle.json"
        metadata = _read_json(metadata_path)
        content_sha256s = metadata["content_sha256s"]
        assert isinstance(content_sha256s, list)
        metadata["provider_device_id"] = None
        metadata["peer_inventory"] = [
            {
                "device_id": DEFAULT_PROVIDER_DEVICE_ID,
                "available_content_sha256": [],
            },
            {
                "device_id": "peer-bundle-untrusted",
                "available_content_sha256": content_sha256s,
            },
        ]
        metadata_path.write_text(json.dumps(metadata), encoding="utf-8")

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_INVENTORY_MISMATCH"
    assert exc.value.details == {
        "provider_device_id": DEFAULT_PROVIDER_DEVICE_ID,
        "provider_inventory_found": True,
        "missing_content_sha256s": sorted(content_sha256s),
    }
    assert staged_count == 0


def test_import_sync_bundle_rejects_provider_from_other_sync_group_before_staging(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-wrong-group"
    with SessionLocal() as session:
        _ensure_trusted_peer(
            session,
            "peer-bundle-other-group",
            sync_group_id="sync_group_other",
        )
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-other-group",
        )
        session.commit()

        monkeypatch.setattr(
            sync_bundle_module,
            "stage_sync_artifact",
            _fail_if_stage_called,
        )
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

        staged_count = session.scalar(select(func.count()).select_from(SyncStagedArtifact))

    assert exc.value.code == "SYNC_BUNDLE_PROVIDER_UNTRUSTED"
    assert staged_count == 0


@pytest.mark.parametrize(
    ("mutation", "expected_code"),
    [
        ("size", "SYNC_BUNDLE_BLOB_SIZE_MISMATCH"),
        ("hash", "SYNC_BUNDLE_BLOB_HASH_MISMATCH"),
    ],
)
def test_import_sync_bundle_rejects_blob_mismatch_before_apply(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    mutation: str,
    expected_code: str,
) -> None:
    bundle_root = tmp_path / f"bundle-{mutation}"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, DEFAULT_PROVIDER_DEVICE_ID)
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )
        session.commit()

        blob_path = _first_blob_path(bundle_root)
        if mutation == "size":
            blob_path.write_bytes(b"x")
        else:
            original_size = blob_path.stat().st_size
            blob_path.write_bytes(b"x" * original_size)

        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == expected_code


def test_import_sync_bundle_rejects_missing_blob_before_apply(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-missing"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, DEFAULT_PROVIDER_DEVICE_ID)
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )
        session.commit()

        _first_blob_path(bundle_root).unlink()
        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == "SYNC_BUNDLE_BLOB_MISSING"


def test_import_sync_bundle_rejects_stale_manifest_metadata_before_apply(
    client: object,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle_root = tmp_path / "bundle-stale-manifest"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, DEFAULT_PROVIDER_DEVICE_ID)
        fixture = _create_project_with_artifacts(session, tmp_path)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
        )
        session.commit()

        manifest_path = bundle_root / "projects" / f"{fixture.project_id}.json"
        manifest_contents = manifest_path.read_text(encoding="utf-8")
        assert "Bundle Fixture" in manifest_contents
        manifest_path.write_text(
            manifest_contents.replace("Bundle Fixture", "Stale Manifest"),
            encoding="utf-8",
        )

        monkeypatch.setattr(
            sync_bundle_module,
            "apply_sync_reconciliation",
            _fail_if_apply_called,
        )
        with pytest.raises(AppError) as exc:
            import_sync_bundle(session, bundle_root=bundle_root)

    assert exc.value.code == "SYNC_BUNDLE_PROJECT_MANIFEST_HASH_MISMATCH"


def test_sync_bundle_preserves_revisions_and_tombstones_round_trip(
    client: object,
    tmp_path: Path,
) -> None:
    bundle_root = tmp_path / "bundle-with-history"
    with SessionLocal() as session:
        _ensure_trusted_peer(session, "peer-bundle-history")
        fixture = _create_project_with_artifacts(session, tmp_path)
        _add_revision_and_tombstone(session, fixture)
        export_sync_bundle(
            session,
            bundle_root=bundle_root,
            project_ids=[fixture.project_id],
            provider_device_id="peer-bundle-history",
        )
        exported_manifest = _read_json(
            bundle_root / "projects" / f"{fixture.project_id}.json"
        )
        sync_group_id = exported_manifest["delete_tombstones"][0]["sync_group_id"]
        session.commit()

        _delete_live_project(session, fixture)
        session.commit()

        result = import_sync_bundle(
            session,
            bundle_root=bundle_root,
            provider_device_id="peer-bundle-history",
        )
        session.commit()

        imported_project = session.get(Project, fixture.project_id)
        imported_revision = session.get(SyncEntityRevision, "rev_bundle_project_metadata")
        imported_tombstone = session.get(SyncDeleteTombstone, "tomb_bundle_deleted_artifact")

    assert exported_manifest["entity_revisions"] == [
        {
            "author_device_id": "device-alpha",
            "base_revision_id": None,
            "content_sha256": revision_payload_sha256(
                {"display_name": "Bundle Synced Fixture"}
            ),
            "created_at": "2026-01-01T00:00:00",
            "entity_id": fixture.project_id,
            "entity_type": "project_metadata",
            "metadata": {"reason": "bundle-round-trip"},
            "payload": {"display_name": "Bundle Synced Fixture"},
            "project_id": fixture.project_id,
            "revision_id": "rev_bundle_project_metadata",
            "revision_type": "edit",
            "source_artifact_id": None,
            "state": CURRENT_REVISION_STATE,
            "updated_at": "2026-01-01T00:00:00",
        }
    ]
    assert exported_manifest["delete_tombstones"] == [
        {
            "author_device_id": "device-alpha",
            "created_at": "2026-01-02T00:00:00",
            "deleted_at": "2026-01-02T00:00:00",
            "prior_metadata": {"type": "preview_mix"},
            "project_id": fixture.project_id,
            "sync_group_id": sync_group_id,
            "target_id": "art_bundle_deleted_preview",
            "target_type": "artifact",
            "tombstone_id": "tomb_bundle_deleted_artifact",
            "updated_at": "2026-01-02T00:00:00",
        }
    ]
    assert result.apply_result.summary.failed_actions == 0
    assert imported_project is not None
    assert imported_project.display_name == "Bundle Synced Fixture"
    assert imported_revision is not None
    assert imported_revision.payload_json == {"display_name": "Bundle Synced Fixture"}
    assert imported_tombstone is not None
    assert imported_tombstone.target_id == "art_bundle_deleted_preview"


def _create_project_with_artifacts(
    session: Session,
    tmp_path: Path,
) -> BundleProjectFixture:
    source_bytes = _wav_bytes(frame_count=96)
    stem_bytes = b"sync bundle stem bytes"
    external_source = tmp_path / "user-library" / f"{hashlib.sha1(source_bytes).hexdigest()}.wav"
    source_sha256, _ = _write_bytes(external_source, source_bytes)
    project_id = source_hash_to_project_id(source_sha256)
    root = project_root(project_id)
    source_relative_path = "source/source.wav"
    stem_relative_path = "stems/vocals.wav"
    source_path = root / source_relative_path
    stem_path = root / stem_relative_path
    source_hash, source_size = _write_bytes(source_path, source_bytes)
    stem_hash, stem_size = _write_bytes(stem_path, stem_bytes)
    timestamp = datetime(2026, 1, 1, tzinfo=UTC)

    session.add(
        Project(
            id=project_id,
            display_name="Bundle Fixture",
            source_key_override="7:minor",
            source_sha256=source_sha256,
            source_path=str(external_source),
            imported_path=str(source_path),
            duration_seconds=1.0,
            sample_rate=44100,
            channels=1,
            created_at=timestamp,
            updated_at=timestamp,
        )
    )
    session.flush()
    session.add_all(
        [
            Artifact(
                id="art_bundle_source",
                project_id=project_id,
                type="source_audio",
                format="wav",
                path=str(source_path),
                content_sha256=source_hash,
                size_bytes=source_size,
                generated_by="import",
                can_delete=False,
                can_regenerate=False,
                metadata_json={"source_label": "bundle"},
                created_at=timestamp,
            ),
            Artifact(
                id="art_bundle_vocals",
                project_id=project_id,
                type="vocals",
                format="wav",
                path=str(stem_path),
                content_sha256=stem_hash,
                size_bytes=stem_size,
                generated_by="stems",
                can_delete=True,
                can_regenerate=True,
                cache_key=f"stem:{project_id}:vocals",
                metadata_json={"source_artifact_id": "art_bundle_source"},
                created_at=timestamp,
            ),
        ]
    )
    session.commit()
    return BundleProjectFixture(
        project_id=project_id,
        root=root,
        source_artifact_id="art_bundle_source",
        stem_artifact_id="art_bundle_vocals",
        source_relative_path=source_relative_path,
        stem_relative_path=stem_relative_path,
        artifact_hashes={
            "art_bundle_source": source_hash,
            "art_bundle_vocals": stem_hash,
        },
        artifact_sizes={
            "art_bundle_source": source_size,
            "art_bundle_vocals": stem_size,
        },
    )


def _add_revision_and_tombstone(
    session: Session,
    fixture: BundleProjectFixture,
) -> None:
    identity = get_or_create_local_identity(session)
    revision_payload = {"display_name": "Bundle Synced Fixture"}
    timestamp = datetime(2026, 1, 1, tzinfo=UTC)
    session.add(
        SyncEntityRevision(
            id="rev_bundle_project_metadata",
            project_id=fixture.project_id,
            entity_type="project_metadata",
            entity_id=fixture.project_id,
            revision_type="edit",
            base_revision_id=None,
            author_device_id="device-alpha",
            source_artifact_id=None,
            content_sha256=revision_payload_sha256(
                sanitize_revision_payload(revision_payload)
            ),
            state=CURRENT_REVISION_STATE,
            metadata_json={"reason": "bundle-round-trip"},
            payload_json=revision_payload,
            created_at=timestamp,
            updated_at=timestamp,
        )
    )
    tombstone_time = datetime(2026, 1, 2, tzinfo=UTC)
    session.add(
        SyncDeleteTombstone(
            id="tomb_bundle_deleted_artifact",
            sync_group_id=identity.sync_group_id,
            project_id=fixture.project_id,
            target_type="artifact",
            target_id="art_bundle_deleted_preview",
            author_device_id="device-alpha",
            deleted_at=tombstone_time,
            prior_metadata_json={"type": "preview_mix"},
            created_at=tombstone_time,
            updated_at=tombstone_time,
        )
    )
    session.commit()


def _ensure_trusted_peer(
    session: Session,
    device_id: str,
    *,
    sync_group_id: str | None = None,
) -> None:
    identity = get_or_create_local_identity(session)
    if session.get(SyncTrustedPeer, device_id) is not None:
        return
    now = datetime.now(UTC)
    session.add(
        SyncTrustedPeer(
            device_id=device_id,
            sync_group_id=sync_group_id or identity.sync_group_id,
            display_name=device_id,
            public_key=f"pub-{device_id}",
            endpoint_hints_json=[],
            trusted_at=now,
            revoked_at=None,
            created_at=now,
            updated_at=now,
        )
    )
    session.commit()


def _delete_live_project(
    session: Session,
    fixture: BundleProjectFixture,
) -> None:
    for revision in session.scalars(
        select(SyncEntityRevision).where(SyncEntityRevision.project_id == fixture.project_id)
    ):
        session.delete(revision)
    for tombstone in session.scalars(
        select(SyncDeleteTombstone).where(SyncDeleteTombstone.project_id == fixture.project_id)
    ):
        session.delete(tombstone)
    for artifact in session.scalars(
        select(Artifact).where(Artifact.project_id == fixture.project_id)
    ):
        session.delete(artifact)
    project = session.get(Project, fixture.project_id)
    if project is not None:
        session.delete(project)
    session.flush()
    shutil.rmtree(fixture.root, ignore_errors=True)


def _first_blob_path(bundle_root: Path) -> Path:
    metadata = _read_json(bundle_root / "bundle.json")
    blob = metadata["blobs"][0]
    return bundle_root / blob["path"]


def _fail_if_apply_called(*_args: Any, **_kwargs: Any) -> None:
    pytest.fail("apply_sync_reconciliation should not be called for invalid bundles")


def _fail_if_stage_called(*_args: Any, **_kwargs: Any) -> None:
    pytest.fail("stage_sync_artifact should not be called for invalid bundles")


def _read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    assert isinstance(payload, dict)
    return payload


def _bundle_files(bundle_root: Path) -> set[str]:
    return {
        path.relative_to(bundle_root).as_posix()
        for path in bundle_root.rglob("*")
        if path.is_file()
    }


def _assert_no_absolute_local_paths(
    payload: dict[str, Any],
    local_roots: Iterable[Path],
) -> None:
    local_root_strings = [str(root) for root in local_roots]
    for value in _iter_strings(payload):
        assert not Path(value).is_absolute(), value
        assert all(root not in value for root in local_root_strings), value


def _assert_no_raw_app_data_entries(payload: dict[str, Any]) -> None:
    forbidden = ("sqlite", ".db", "settings", "appdata", "app-data", "/cache", "\\cache")
    for value in _iter_strings(payload):
        normalized = value.lower()
        assert all(fragment not in normalized for fragment in forbidden), value


def _iter_strings(value: Any) -> Iterator[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for child in value.values():
            yield from _iter_strings(child)
    elif isinstance(value, list):
        for child in value:
            yield from _iter_strings(child)


def _write_bytes(path: Path, contents: bytes) -> tuple[str, int]:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(contents)
    content_hash = file_sha256(path)
    assert content_hash is not None
    return content_hash, path.stat().st_size


def _wav_bytes(*, frame_count: int, sample_rate: int = 44100) -> bytes:
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)
        wav_file.writeframes(b"\0\0" * frame_count)
    return buffer.getvalue()
