version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directory: "/apps/desktop"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directory: "/packages/shared-types"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: pip
    directory: "/apps/backend"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: cargo
    directory: "/apps/desktop/src-tauri"
    patterns:
      - "*"
    multi-ecosystem-group: dependencies
